dependencies:
  - python = 3
  - pip:
      - spacy
      - ipykernel
      - scipy
      - numpy
      - scikit-learn
      - matplotlib
      - pandas
      - thinc
      - theano
      - tensorflow
      - mkl
      - libblas-dev
      - liblapack-dev
      - libblas-base-dev
      - gfortran
